version: '3'
services:
    django-tutorial:
      build: /
      restart: always
      command: python /home/azureuser/Django-Tutorial/manage.py runserver 0.0.0.0:8000
      ports:
        - "8002:8000"
      volumes:
        - /home/azureuser/Django-Tutorial:/storage

    jenkins:
          image: jenkins/jenkins:lts-jdk11
          restart: always
          ports:
              - "8081:8080"
              - "50001:50000"
          volumes:
              - /home/azureuser/jenkins:/var/jenkins_home
volumes:
    pgdata_jenkins_host:
