name: Deploy to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip git -y
        sudo pip3 install virtualenv
        python3 -m virtualenv venv
        source venv/bin/activate
        pip3 install -r requirements.txt

    - name: Deploy code
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./*"
        target: "/home/user/myapp/"
