# Generated by Django 4.0.6 on 2023-03-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time'], 'permissions': (('can_comment', 'Can comment'),)},
        ),
    ]
